<?php
namespace Procountor\Interfaces;

use DateTime;
use Procountor\Collection\TransactionCollection;

interface LedgerReceiptCommon extends AbstractResourceInterface {

    //Ledger receipt type. Use JOURNAL for creating ledger receipts (vouchers) containing ledger transactions without linkage to pre-existing resources. Other types are automatically generated by Procountor for holding accounting information for e.g. invoices. = ['JOURNAL', 'SALES_INVOICE', 'PURCHASE_INVOICE'],
    public function getType(): string;


    //Ledger receipt status. Status of a ledger receipt equals the status of the linked invoice. All ledger receipts are initially created with status UNFINISHED. For journals, possible statuses are UNFINISHED, APPROVED and INVALIDATED. Ledger receipt statuses cannot be directly modified through the API. = ['EMPTY', 'UNFINISHED', 'NOT_SENT', 'SENT', 'RECEIVED', 'PAID', 'PAYMENT_DENIED', 'VERIFIED', 'APPROVED', 'INVALIDATED', 'PAYMENT_QUEUED', 'PARTLY_PAID', 'PAYMENT_SENT_TO_BANK', 'MARKED_PAID', 'STARTED', 'INVOICED', 'OVERRIDDEN', 'DELETED', 'UNSAVED', 'PAYMENT_TRANSACTION_REMOVED'],
    public function getStatus(): ?string;

    //Ledger receipt name. Max length 80. ,
    public function getName(): string;

    //Ledger receipt date. Must not be in a closed fiscal period. See GET /fiscalyears for a list of fiscal years. ,
    public function getReceiptDate(): Datetime;

    //Ledger receipt VAT type. = ['SALES', 'PURCHASE'],
    public function getVatType(): string;

    //Ledger receipt VAT country. Example: SWEDEN. Only for JOURNAL types of ledger receipts. Requires a special right for foreign VATs. = ['See Address.country in POST /invoices for a list of allowable values.'],
    public function getVatProcessing(): ?string;

    //Invoice notes. Linked to Invoice.notes. Not visible on ledger receipt printouts. Use \n as line break. Max length 10000. ,
    public function getInvoiceNotes(): ?string;

    //Notes made by the accountant. Visible on ledger receipt printouts. Max length 255. ,
    public function getAccountantsNotes(): ?string;

    //Transaction description. This is a summary description for any transactions belonging to the ledger receipt. Max length 255. ,
    public function getTransactionDescription(): ?string;

    //Receipt validity time. = ['EMPTY', 'IMMEDIATELY', 'SERVICE_PERIOD', 'OVER_3_YEARS'],
    public function getReceiptValidity(): ?string;

    //Start date of the receipt period. If set, must precede the end date of the period. ,
    public function getPeriodStartDate(): ?Datetime;

    //End date of the receipt period. If this and the start date are set, this must be after the start date. ,
    public function getPeriodEndDate(): ?Datetime;

    //Partner code. Identifier for the related company or person. May represent a business ID, national identification number (HETU in Finland) or an account number, depending on the receipt type. ,
    public function getPartnerCode(): ?string;

    //Ledger receipt version timestamp. Automatically generated by Procountor and updated every time the receipt is modified. When using PUT /ledgerreceipts, it is required to include the latest version timestamp of the receipt to the request. This prevents conflicts if the receipt is being modified from several sources. ,
    public function getVersion(): string;

    //Accounting depreciation method for the receipt. = ['EMPTY', 'REDUCING_BALANCE_25_PERCENT', 'REDUCING_BALANCE_7_PERCENT', 'REDUCING_BALANCE_4_PERCENT', 'STRAIGHT_LINE_DEPRECIATION_3_YEARS', 'STRAIGHT_LINE_DEPRECIATION_5_YEARS'],
    public function getDepreciation(): ?string;

    //VAT date to be used if payment based VAT is enabled ,
    public function getVatDate(): ?Datetime;

    //List containing transactions on the receipt. At least one transaction must be provided. ,
    public function getTransactions(): TransactionCollection;
}
