<?php

namespace Procountor\Procountor\Interfaces\Read;

use Procountor\Procountor\Interfaces\AttachmentCommon;

interface Attachment extends AttachmentCommon
{

    /**
     * Unique identifier of the attachment. Generated by Procountor and present in the object returned.
     *
     * @return int
     */
    public function getId(): int;

    /**
     * Mime type of the attachment. Determined from the file extension.
     * @see http://www.freeformatter.com/mime-types-list.html
     *
     * @return string
     */
    public function getMimeType(): string;
}
