<?php
namespace Procountor\Interfaces\Read;

use Procountor\Interfaces\AttachmentCommon;

interface Attachment extends AttachmentCommon {

    //Unique identifier of the attachment. Generated by Procountor and present in the object returned. ,
    public function getId(): int;


    //Mime type of the attachment. Determined from the file extension. For more info, see for example: http://www.freeformatter.com/mime-types-list.html.
    public function getMimeType(): string;
}

