<?php
namespace Procountor\Interfaces\Read;

use Procountor\Interfaces\BusinessPartnerCommon;
use Procountor\Collection\AttachmentCollection;

interface BusinessPartner extends BusinessPartnerCommon {
    //Unique identifier of the business partner. Generated by Procountor and present in the object returned. ,
    public function getId(): int;
}
