<?php

namespace Procountor\Procountor\Interfaces\Read;

use Procountor\Procountor\Interfaces\BusinessPartnerCommon;
use Procountor\Procountor\Collection\AttachmentCollection;

interface BusinessPartner extends BusinessPartnerCommon
{
    /**
     * Unique identifier of the business partner. Generated by Procountor and present in the object returned.
     *
     * @return int
     */
    public function getId(): int;
}
