<?php

namespace Procountor\Procountor\Interfaces\Read;

use Procountor\Procountor\Interfaces\InvoiceCommon;
use Procountor\Procountor\Collection\AttachmentCollection;

interface Invoice extends InvoiceCommon
{

    //Unique identifier of the invoice. Generated by Procountor and present in the object returned. ,
    public function getId(): int;

    //Invoice number generated by Procountor. For custom invoice numbers, see the originalInvoiceNumber property.
    public function getInvoiceNumber(): int;

    //ID of the ledger receipt linked to this invoice. A ledger receipt is linked to every invoice for holding its accounting information. For defining ledger accounts, dimensions or VAT status regarding the invoice, modify the ledger receipt. See PUT /ledgerreceipts for more info. ,
    public function getLedgerReceiptId(): ?int;

    //Only for invoice type PERIODIC_TAX_RETURN. Ignored for other types. Contains the total sum of invoice. ,
    public function getSum(): ?string;

    //List of attachments added to this invoice. Use POST and DELETE /attachments to add and delete attachments.
    public function getAttachments(): ?AttachmentCollection;
}
